name: CI

on:
  push:
    branches: [ master ]

jobs:
  build_deploy:
    name: Build & Deploy to Firebase
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repo
      uses: actions/checkout@master
    
    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy to Firebase
      run: npm run deploy:ci
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      

