name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist

  deploy:
    name: Deploy to Firebase
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm install
    
    - name: Download production artifacts
      uses: actions/download-artifact@v2
      with:
        name: dist
        path: dist

    - name: Deploy to Firebase
      run: npm run deploy:ci
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      

